package main
var (
	//from 3 to 8 : don't mean anything, just numbers
	maxPowerForBrazil = 8
	maxPowerForRussia = 5
	maxPowerForFrance = 3
)

var BTSSongs = map[string]int{
	"We Are Bulletproof Pt.2": 6,
	"No More Dream": 6,
	"N.O": 4,
	"진격의 방탄 Attack on Bangtan": 4,
	"상남자 Boy In Luv": 7,
	"하루만 Just One Day": 5,
	"Tomorrow": 3,
	"등골브레이커 Spine Breaker": 8,
	"Jump": 8,
	"Danger": 7,
	"War Of Hormone": 9,
	"여기 봐 Look here": 4,
	"24/7=heaven": 1,
	"Born Singer": 2,
	"I NEED U": 5,
	"잡아줘 Hold Me Tight": 2,
	"쩔어 DOPE": 4,
	"흥탄소년단 Boyz With Fun": 3,
	"Converse High": 4,
	"이사 Moving On": 4,
	"Outro: Love is Not Over": 3,
	"FOR YOU": 1,
	"Ostukare": 5,
	"RUN": 7,
	"Butterfly": 3,
	"Ma City": 1,
	"Baepsae": 5,
	"OUTRO: House Of Cards": 4,
	"불타오르네 FIRE": 7,
	"Save Me": 8,
	"EPILOGUE: Young Forever": 8,
	"Intro: Boy Meets Evil": 7,
	"Blood Sweat & Tears": 9,
	"Begin": 4,
	"Lie": 2,
	"MAMA": 1,
	"Awake": 2,
	"Lost": 1,
	"BTS Cypher 4": 7,
	"Tony Montana": 3,
	"Agust D": 1,
	"Am I Wrong": 2,
	"21st Century Girl 21세기 소녀": 4,
	"Two! Three! (Hoping for Better Days)": 5,
	"Interlude: Wings": 3,
	"봄날 Spring Day": 9,
	"Not Today": 8,
	"Intro: Serendipity": 1,
	"DNA": 3,
	"Best Of Me": 4,
	"보조개 Dimple": 5,
	"Pied Piper": 3,
	"MIC Drop": 9,
	"고민보다 Go Go": 8,
	"CRYSTAL SNOW": 3,
	"Don’t Leave Me": 1,
	"Let Go": 5,
	"Fake Love": 7,
	"전하지 못한 진심 The Truth Untold": 8,
	"134340": 3,
	"Intro: Singularity": 2,
	"낙원 Paradise": 3,
	"Love Maze": 6,
	"Magic Shop": 7,
	"Airplane Pt. 2": 5,
	"Anpanman": 8,
	"So What": 9,
	"Outro: Tear": 7,
	"Euphoria": 8,
	"Trivia 起: Just Dance": 5,
	"Trivia 承: Love": 4,
	"Trivia 轉: Seesaw": 5,
	"Epiphany": 8,
	"I’m Fine": 7,
	"IDOL": 9,
	"Answer: Love Myself": 3,
	"Best of Me": 6,
	"MIC Drop [Steve Aoki Remix] (Full Length Edition)": 9,
	"작은 것들을 위한 시 (Boy With Luv) feat. Halsey": 5,
	"소우주 (Mikrokosmos)": 8,
	"Make It Right": 7,
	"HOME": 6,
	"Jamais Vu": 3,
	"Dionysus": 5,
	"Dream Glow": 3,
	"A Brand New Day": 7,
	"Heartbeat": 8,
	"Lights": 5,
	"Black Swan": 7,
	"Filter": 5,
	"My Time": 2,
	"Louder than bombs": 9,
	"ON": 8,
	"UGH!": 7,
	"00:00 (Zero O’Clock)": 6,
	"Inner Child": 5,
	"Friends": 5,
	"Moon": 9,
	"Respect": 3,
	"We are Bulletproof: the Eternal": 5,
	"Outro: Ego": 4,
	"Interlude: Shadow": 5,
	"Stay Gold": 3,
	"Your Eyes Tell": 1,
	"Life Goes On": 2,
	"Fly To My Room": 2,
	"Blue & Grey": 3,
	"Telepathy": 4,
	"Dis-ease": 7,
	"Stay": 4,
	"Dynamite": 8,
	"Film Out": 4,
	"Butter": 7,
	"Permission to Dance": 6,
	"Do You": 5,
	"Give It To Me": 7,
	"Base Line": 5,
	"Hope World": 8,
	"Daydream (백일몽)": 4,
	"항상 (HANGSANG) (Ft. Supreme Boi)": 5,
	"Airplane": 4,
	"Blue Side (Outro)": 6,
	"Tokyo": 4,
	"Seoul": 3,
	"Moonchild": 2,
	"지나가 (everythingoes) (Ft. 넬 Nell (KR)": 5,
	"Forever Rain": 3,
	"Daechwita": 8,
	"What do you think?": 5,
	"28 (Ft. NiiHWA)": 9,
	"Burn It (Ft. MAX)": 1,
	"People": 3,
	"Honsool": 4,
	"Interlude: Set me free": 5,
	"Dear my friend (Ft. Kim Jong Wan)": 6,
	"IF YOU": 9,
	"Chicken Noodle Soup": 7,
	"Still with you": 8,
	"Bicycle": 5,
	"Snow flower": 4,
	"Ddaeng": 8,
	"Winter Flower": 4,
	"Sweet Night": 7,
}
